In [1]:
import numpy as np

lam = 180
pClass1 = [[1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 1]]
pClass2 = [[1, 0, 0, 0, 0], [0, 0.8, 0.2, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0]]
pClass3 = [[1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [0, 0.5, 0.5, 0, 0]]
pClass4 = [[1, 0, 0, 0, 0], [0, 0.4, 0.6, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]]
p = [pClass1, pClass2, pClass3, pClass4]
p

[[[1, 0, 0, 0, 0],
  [0, 0, 0, 1, 0],
  [0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0],
  [0, 0, 0, 0, 1]],
 [[1, 0, 0, 0, 0],
  [0, 0.8, 0.2, 0, 0],
  [0, 0, 0, 0, 1],
  [0, 0, 0, 0, 1],
  [0, 0, 0, 0, 0]],
 [[1, 0, 0, 0, 0],
  [0, 0, 0, 1, 0],
  [0, 0, 0, 0, 1],
  [0, 0, 0, 0, 1],
  [0, 0.5, 0.5, 0, 0]],
 [[1, 0, 0, 0, 0],
  [0, 0.4, 0.6, 0, 0],
  [0, 0, 0, 1, 0],
  [0, 0, 0, 1, 0],
  [0, 0, 0, 0, 1]]]

In [2]:
lambdas0 = []
for r in range(4):
    lambdas0
    for i in range(5):
        lambdas0.append(lam*p[r][0][i])
lambdas0

[180, 0, 0, 0, 0, 180, 0, 0, 0, 0, 180, 0, 0, 0, 0, 180, 0, 0, 0, 0]

In [3]:
lambda_ir = np.zeros([5,4])
lambda_ir[0,0] = lam
lambda_ir[0,1] = lam
lambda_ir[0,2] = lam
lambda_ir[0,3] = lam
#
lambda_ir[1,0] = 0
lambda_ir[1,1] = lam * 0.8
lambda_ir[1,2] = lam * 0.5
lambda_ir[1,3] = lam * 0.4
#
lambda_ir[2,0] = 0
lambda_ir[2,1] = lam * 0.2
lambda_ir[2,2] = lam * 0.5
lambda_ir[2,3] = lam * 0.6
#
lambda_ir[3,0] = lam
lambda_ir[3,1] = 0
lambda_ir[3,2] = lam
lambda_ir[3,3] = 0.4 * lam + 0.6 * lam
#
lambda_ir[4,0] = lam
lambda_ir[4,1] = lam
lambda_ir[4,2] = lam
lambda_ir[4,3] = lam

In [4]:
lambda_ir

array([[180., 180., 180., 180.],
       [  0., 144.,  90.,  72.],
       [  0.,  36.,  90., 108.],
       [180.,   0., 180., 180.],
       [180., 180., 180., 180.]])

In [49]:
#Do not run
A = np.zeros([20,20])
for r in range(4):
    for i in range(5):
        A[r*5 + i, 0] = 1
        for j in range(1, 6):
            A[r*5 + i,j] = -p[r][i][j - 1]       
A            

array([[ 1. , -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. , -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. , -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. , -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. , -0.8, -0.2,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. , -1.

In [5]:
m_i = [1, 1, 1, 4, 1]
mi_ir = np.zeros([5,4])
mi_ir[0,:] = np.array([150, 150, 150, 150])
mi_ir[1,:] = np.array([0, 120, 120, 120])
mi_ir[2,:] = np.array([0, 100, 100, 100])
mi_ir[3,:] = np.array([95, 0, 95, 95])
mi_ir[4,:] = np.array([120, 120, 120, 120])
mi_ir

array([[150., 150., 150., 150.],
       [  0., 120., 120., 120.],
       [  0., 100., 100., 100.],
       [ 95.,   0.,  95.,  95.],
       [120., 120., 120., 120.]])

In [50]:
ro_ir = np.zeros([5, 4])
for i in range(5):
    for r in range(4):
        ro_ir[i,r] = lambda_ir[i,r] / (m_i[i] * mi_ir[i,r])
ro_ir = np.nan_to_num(ro_ir)
np.set_printoptions(precision = 3)
ro_ir

<ipython-input-50-3485cc2c3808>:4: RuntimeWarning: invalid value encountered in double_scalars
  ro_ir[i,r] = lambda_ir[i,r] / (m_i[i] * mi_ir[i,r])


array([[1.2  , 1.2  , 1.2  , 1.2  ],
       [0.   , 1.2  , 0.75 , 0.6  ],
       [0.   , 0.36 , 0.9  , 1.08 ],
       [0.474, 0.   , 0.474, 0.474],
       [1.5  , 1.5  , 1.5  , 1.5  ]])

In [56]:
ro_ir = [[0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2],
        [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2]]
ro_ir

[[0.2, 0.2, 0.2, 0.2],
 [0.2, 0.2, 0.2, 0.2],
 [0.2, 0.2, 0.2, 0.2],
 [0.2, 0.2, 0.2, 0.2],
 [0.2, 0.2, 0.2, 0.2]]

In [57]:
def calculate_pi_k_i(ro_i, k_i, m_i):
    if m_i == 1:
        return (1 - ro_i)*ro_i**k_i
    else:
        sum_ = 0
        for i in range(m_i):
            sum_ += (m_i*ro_i)**i/np.math.factorial(i)
        sum_ += (m_i*ro_i)**m_i/(np.math.factorial(m_i)*(1 - ro_i))
        if k_i <= m_i:
            return 1/sum_*(m_i*ro_i)**k_i/np.math.factorial(k_i)
        else:
            return 1/sum_*m_i**m_i*ro_i**k_i/np.math.factorial(m_i)

In [58]:
def calculate_pi_k(pi_i):
    result = 1
    for pi in pi_i:
        result *= pi
    return result

In [59]:
def calculate_ro_i(i):
    return np.sum(ro_ir[i])

In [60]:
probs = []
for i in range(5):
    probs_i = []
    for k in range(10):
        probs_i.append(calculate_pi_k_i(calculate_ro_i(i), k, m_i[i]))
    probs.append(probs_i)
probs

[[0.19999999999999996,
  0.15999999999999998,
  0.128,
  0.1024,
  0.08191999999999999,
  0.065536,
  0.05242880000000001,
  0.04194304000000001,
  0.03355443200000001,
  0.026843545600000008],
 [0.19999999999999996,
  0.15999999999999998,
  0.128,
  0.1024,
  0.08191999999999999,
  0.065536,
  0.05242880000000001,
  0.04194304000000001,
  0.03355443200000001,
  0.026843545600000008],
 [0.19999999999999996,
  0.15999999999999998,
  0.128,
  0.1024,
  0.08191999999999999,
  0.065536,
  0.05242880000000001,
  0.04194304000000001,
  0.03355443200000001,
  0.026843545600000008],
 [0.02730251183108845,
  0.08736803785948305,
  0.1397888605751729,
  0.14910811794685108,
  0.11928649435748086,
  0.0954291954859847,
  0.07634335638878777,
  0.06107468511103021,
  0.04885974808882418,
  0.039087798471059344],
 [0.19999999999999996,
  0.15999999999999998,
  0.128,
  0.1024,
  0.08191999999999999,
  0.065536,
  0.05242880000000001,
  0.04194304000000001,
  0.03355443200000001,
  0.026843545600000

In [20]:
calculate_pi_k_i(4.8, 0, 1)

-3.8