In [1]:
import numpy as np

lam = 180
pClass1 = [[1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 1]]
pClass2 = [[1, 0, 0, 0, 0], [0, 0.8, 0.2, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0]]
pClass3 = [[1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [0, 0.5, 0.5, 0, 0]]
pClass4 = [[1, 0, 0, 0, 0], [0, 0.4, 0.6, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]]
p = [pClass1, pClass2, pClass3, pClass4]
p

[[[1, 0, 0, 0, 0],
  [0, 0, 0, 1, 0],
  [0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0],
  [0, 0, 0, 0, 1]],
 [[1, 0, 0, 0, 0],
  [0, 0.8, 0.2, 0, 0],
  [0, 0, 0, 0, 1],
  [0, 0, 0, 0, 1],
  [0, 0, 0, 0, 0]],
 [[1, 0, 0, 0, 0],
  [0, 0, 0, 1, 0],
  [0, 0, 0, 0, 1],
  [0, 0, 0, 0, 1],
  [0, 0.5, 0.5, 0, 0]],
 [[1, 0, 0, 0, 0],
  [0, 0.4, 0.6, 0, 0],
  [0, 0, 0, 1, 0],
  [0, 0, 0, 1, 0],
  [0, 0, 0, 0, 1]]]

In [45]:
lambdas0 = []
for r in range(4):
    lambdas0
    for i in range(5):
        lambdas0.append(lam*p[r][0][i])
lambdas0

[180, 0, 0, 0, 0, 180, 0, 0, 0, 0, 180, 0, 0, 0, 0, 180, 0, 0, 0, 0]

In [47]:
lambda_ir = np.zeros([5,4])
lambda_ir[0,0] = lam
lambda_ir[0,1] = lam
lambda_ir[0,2] = lam
lambda_ir[0,3] = lam
#
lambda_ir[1,0] = 0
lambda_ir[1,1] = lam * 0.8
lambda_ir[1,2] = lam * 0.5
lambda_ir[1,3] = lam * 0.4
#
lambda_ir[2,0] = 0
lambda_ir[2,1] = lam * 0.2
lambda_ir[2,2] = lam * 0.5
lambda_ir[2,3] = lam * 0.6
#
lambda_ir[3,0] = lam
lambda_ir[3,1] = 0
lambda_ir[3,2] = lam
lambda_ir[3,3] = 0.4 * lam + 0.6 * lam
#
lambda_ir[4,0] = lam
lambda_ir[4,1] = lam
lambda_ir[4,2] = lam
lambda_ir[4,3] = lam

In [48]:
lambda_ir

array([[180., 180., 180., 180.],
       [  0., 144.,  90.,  72.],
       [  0.,  36.,  90., 108.],
       [180.,   0., 180., 180.],
       [180., 180., 180., 180.]])

In [49]:
#Do not run
A = np.zeros([20,20])
for r in range(4):
    for i in range(5):
        A[r*5 + i, 0] = 1
        for j in range(1, 6):
            A[r*5 + i,j] = -p[r][i][j - 1]       
A            

array([[ 1. , -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. , -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. , -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. , -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. , -0.8, -0.2,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. , -1.

In [51]:
m_i = [1, 1, 1, 4, 1]
mi_ir = np.zeros([5,4])
mi_ir[0,:] = np.array([150, 150, 150, 150])
mi_ir[1,:] = np.array([0, 120, 120, 120])
mi_ir[2,:] = np.array([0, 100, 100, 100])
mi_ir[3,:] = np.array([95, 0, 95, 95])
mi_ir[4,:] = np.array([120, 120, 120, 120])
mi_ir

array([[150., 150., 150., 150.],
       [  0., 120., 120., 120.],
       [  0., 100., 100., 100.],
       [ 95.,   0.,  95.,  95.],
       [120., 120., 120., 120.]])

In [54]:
ro_ir = np.zeros([5, 4])
for i in range(5):
    for r in range(4):
        ro_ir[i,r] = lambda_ir[i,r] / (m_i[i] * mi_ir[i,r])
ro_ir = np.nan_to_num(ro_ir)
ro_ir

C:\Users\kubag\Anaconda3\envs\deeplearning\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in double_scalars
  after removing the cwd from sys.path.


array([[1.2       , 1.2       , 1.2       , 1.2       ],
       [0.        , 1.2       , 0.75      , 0.6       ],
       [0.        , 0.36      , 0.9       , 1.08      ],
       [0.47368421, 0.        , 0.47368421, 0.47368421],
       [1.5       , 1.5       , 1.5       , 1.5       ]])

In [ ]:
def calculate_pi_k(i, k, m):
    